version: '3'
services:
  frontend-blue:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production

  frontend-green:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "3002:3000"
    environment:
      - NODE_ENV=production
