name: React Vite CI/CD

on:
  push:
    branches: [ "main", "release" ]
  pull_request:
    branches: [ "main", "release" ]

jobs:
  build:
    if: github.repository == 'deveunhwa/bitta-front'
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      # 코드 체크아웃
      - uses: actions/checkout@v4

      # Node.js 환경 설정 (Vite는 Node.js가 필요)
      - name: Set up Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: '18'  # Vite의 요구사항에 따라 Node.js 버전을 설정

      # 의존성 설치
      - name: Install dependencies
        run: npm install

      # 빌드 실행
      - name: Build project
        run: npm run build  # Vite의 기본 빌드 명령어, 빌드 결과는 기본적으로 dist 폴더에 생성됨

  deploy:
    if: github.repository == 'your-username/your-frontend-repo' && github.ref == 'refs/heads/release'
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      # Docker Hub 로그인
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Docker 이미지 빌드 및 푸시
      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/bitta-front:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/bitta-front:latest

      # EC2 서버에 배포
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
            docker pull ${{ secrets.DOCKER_USERNAME }}/bitta-front:latest
            docker stop frontend-container || true
            docker rm frontend-container || true
            docker run -d --name frontend-container -p 3000:80 ${{ secrets.DOCKER_USERNAME }}/bitta-front:latest
