name: React Vite CI/CD

on:
  push:
    branches: [ "main", "release" ]
  pull_request:
    branches: [ "main", "release" ]

jobs:
  build:
    if: github.repository == 'deveunhwa/bitta-front'
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      # 1. 코드 체크아웃
      - uses: actions/checkout@v4

      # 2. Node.js 환경 설정 (Vite는 Node.js가 필요)
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16'  # Vite의 요구사항에 따라 Node.js 버전을 설정

      # 3. 의존성 설치
      - name: Install dependencies
        run: npm install

      # 4. 빌드 실행
      - name: Build project
        run: npm run build  # Vite의 기본 빌드 명령어, 빌드 결과는 기본적으로 dist 폴더에 생성됨

      # 5. S3 배포
      - name: Deploy to S3
        if: github.ref == 'refs/heads/release'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'ap-northeast-2'  # AWS 리전 정보
        run: aws s3 sync ./dist s3://your-frontend-bucket-name --delete

      # 6. CloudFront 캐시 무효화
      - name: Invalidate CloudFront Cache
        if: github.ref == 'refs/heads/release'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          DISTRIBUTION_ID: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
        run: |
          aws cloudfront create-invalidation \
            --distribution-id $DISTRIBUTION_ID \
            --paths "/*"
